#!/bin/sh

echo -n "   Reload Dunst? [Y/n] "
read -r ans
if [[ "$ans" =~ ^[Yy]$ || "$ans" == "" ]]; then
	pkill dunst &&
	dunst & disown
	sleep 0.1;
	echo -n "   Done"
	sleep 0.1;
else
	continue
fi

dunstify "asdasd" -t 10000 -u low
dunstify "asdasd" -t 10000 -u normal
dunstify "asdasd" -t 10000 -u critical
